spring.application.name=cp2brinquedos
# Configurações de Conexão com o Oracle FIAP
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm563405
spring.datasource.password=250307
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true